### ISSUE TITLE
Duplicate DimensionManager

### ISSUE THREAD

**Issue by eccentricdevotion** [TBMCPlugins/CustomDimensions#1]
Getting an error when enabling the plugin.
- My datapacks do not have a dimension called `single_biome` - I presume it is added by Bukkiit?
- My custom dimensions load fine :)

Server info:
- Paper version git-Paper-192 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
- System Info: Java 14 (Java HotSpot(TM) 64-Bit Server VM 14.0.2+12-46) Host: Mac OS X 10.15.6 (x86_64)

```
[22:42:40 INFO]: [CustomDimensions] Loading single_biome
[22:42:40 ERROR]: Adding duplicate value 'net.minecraft.server.v1_16_R2.DimensionManager@63fa0b9' to registry
[22:42:40 WARN]: java.lang.IllegalArgumentException: value already present: net.minecraft.server.v1_16_R2.DimensionManager@63fa0b9
[22:42:40 WARN]: 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287)
[22:42:40 WARN]: 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262)
[22:42:40 WARN]: 	at net.minecraft.server.v1_16_R2.RegistryMaterials.a(RegistryMaterials.java:87)
[22:42:40 WARN]: 	at net.minecraft.server.v1_16_R2.RegistryMaterials.a(RegistryMaterials.java:122)
[22:42:40 WARN]: 	at buttondevteam.customdimensions.CustomDimensions.load(CustomDimensions.java:95)
[22:42:40 WARN]: 	at buttondevteam.customdimensions.CustomDimensions.onEnable(CustomDimensions.java:24)
[22:42:40 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[22:42:40 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[22:42:40 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[22:42:40 WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499)
[22:42:40 WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413)
[22:42:40 WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
[22:42:40 WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241)
[22:42:40 WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
[22:42:40 WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[22:42:40 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by NorbiPeti** [comment]
That's strange, do you have a world named single_biome or any plugins that might load a world/dimension? What plugins do you use? I just tested with Paper 192 and I'm not getting this.

**Comment by eccentricdevotion** [comment]
- No worlds named `single_biome`
- Other worlds are loaded by the TARDIS plugin - https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/planets/TARDISWorlds.java#L40

I'll do some more testing without TARDIS... and with a fresh server install

**Comment by eccentricdevotion** [comment]
Did some more testing and not getting the error with a fresh server setup and the TARDIS plugin installed.
I think this must be a hang over from a previous 1.15 'buffet' style world that was on the original test server.
I'll close this for now, but will keep an eye on things...
