### ISSUE TITLE
cant get it to work

### ISSUE THREAD

**Issue by DabbingEevee** [TBMCPlugins/CustomDimensions#5]
[09:07:46 ERROR]: Could not load 'plugins/CustomDimensions-1.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/minecraft/class_32$class_5143
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.3.jar:git-Paper-207]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.3.jar:git-Paper-207]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.3.jar:git-Paper-207]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.3.jar:git-Paper-207]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:204) ~[patched_1.16.3.jar:git-Paper-207]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-207]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-207]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_32$class_5143
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.3.jar:git-Paper-207]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.3.jar:git-Paper-207]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_32$class_5143
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.16.3.jar:git-Paper-207]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.3.jar:git-Paper-207]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.3.jar:git-Paper-207]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.3.jar:git-Paper-207]
	... 7 more

**Comment by NorbiPeti** [comment]
The latest version (1.4) only supports Minecraft 1.16.4. You need to either update your server or if you can't for some reason, then use the [1.3](https://www.spigotmc.org/resources/1-16-custom-dimensions.83731/download?version=358334) version of the plugin (however, dimensions that don't have a custom dimension type will only work in 1.4).
