### ISSUE TITLE
Not working on 1.16.5

### ISSUE THREAD

**Issue by maicol07** [TBMCPlugins/CustomDimensions#8]
It doesn't work with this datapack: planetminecraft.com/data-pack/dungeon-now-loading-5-new-dungeons-5-new-bosses

Using Paper server

Crash report:

```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 01/03/21, 16:47
Description: Exception in server tick loop

java.lang.IllegalStateException: Unregistered dimension type: net.minecraft.server.v1_16_R3.DimensionManager@2a593c7c
	at net.minecraft.server.v1_16_R3.World.lambda$new$0(World.java:136)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
	at net.minecraft.server.v1_16_R3.World.<init>(World.java:135)
	at net.minecraft.server.v1_16_R3.WorldServer.<init>(WorldServer.java:211)
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:432)
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:941)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
	at java.base/java.lang.Thread.run(Thread.java:832)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.4.0-66-generic
	Java Version: 14.0.2, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 724232192 bytes (690 MB) / 1073741824 bytes (1024 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xms1G -Xmx4G
	CraftBukkit Information: 
   Running: Paper version git-Paper-505 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) true
   Plugins: { CustomDimensions v1.5 buttondevteam.customdimensions.CustomDimensions [],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { RUNNABLE Notification Thread: [], TIMED_WAITING Craft Scheduler Thread - 0: [java.base@14.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@14.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@14.0.2/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462), java.base@14.0.2/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361), java.base@14.0.2/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1055), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1116), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630), java.base@14.0.2/java.lang.Thread.run(Thread.java:832)], RUNNABLE Server console handler: [java.base@14.0.2/java.io.FileInputStream.read0(Native Method), java.base@14.0.2/java.io.FileInputStream.read(FileInputStream.java:224), app//org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73), app//org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62), app//org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168), app//org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57), app//org.jline.keymap.BindingReader.readCharacter(BindingReader.java:133), app//org.jline.keymap.BindingReader.readBinding(BindingReader.java:110), app//org.jline.keymap.BindingReader.readBinding(BindingReader.java:61), app//org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:848), app//org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:868), app//org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:575), app//org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418), app//net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158), app//net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141), app//net.minecraft.server.v1_16_R3.DedicatedServer$1.run(DedicatedServer.java:67)], TIMED_WAITING Craft Scheduler Thread - 1: [java.base@14.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@14.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@14.0.2/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462), java.base@14.0.2/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361), java.base@14.0.2/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1055), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1116), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630), java.base@14.0.2/java.lang.Thread.run(Thread.java:832)], WAITING Paper Async Chunk Task Thread #0: [java.base@14.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@14.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], WAITING Worker-Main-1: [java.base@14.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@14.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@14.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:505), java.base@14.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3137), java.base@14.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1614), java.base@14.0.2/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1056), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1116), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630), java.base@14.0.2/java.lang.Thread.run(Thread.java:832)], RUNNABLE Reference Handler: [java.base@14.0.2/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@14.0.2/java.lang.ref.Reference.processPendingReferences(Reference.java:241), java.base@14.0.2/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)], TIMED_WAITING Common-Cleaner: [java.base@14.0.2/java.lang.Object.wait(Native Method), java.base@14.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@14.0.2/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148), java.base@14.0.2/java.lang.Thread.run(Thread.java:832), java.base@14.0.2/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)], WAITING Paper Async Chunk Urgent Task Thread: [java.base@14.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@14.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], TIMED_WAITING pool-4-thread-1: [java.base@14.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@14.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@14.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1661), java.base@14.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@14.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1056), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1116), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630), java.base@14.0.2/java.lang.Thread.run(Thread.java:832)], TIMED_WAITING Timer hack thread: [java.base@14.0.2/java.lang.Thread.sleep(Native Method), app//net.minecraft.server.v1_16_R3.SystemUtils$5.run(SystemUtils.java:465)], TIMED_WAITING Craft Scheduler Thread - 2: [java.base@14.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@14.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@14.0.2/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462), java.base@14.0.2/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361), java.base@14.0.2/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1055), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1116), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630), java.base@14.0.2/java.lang.Thread.run(Thread.java:832)], RUNNABLE Server thread: [java.base@14.0.2/java.lang.Thread.dumpThreads(Native Method), java.base@14.0.2/java.lang.Thread.getAllStackTraces(Thread.java:1649), app//org.bukkit.craftbukkit.v1_16_R3.CraftCrashReport.call(CraftCrashReport.java:33), app//net.minecraft.server.v1_16_R3.CrashReportSystemDetails.a(SourceFile:79), app//net.minecraft.server.v1_16_R3.CrashReport.i(CrashReport.java:71), app//net.minecraft.server.v1_16_R3.CrashReport.<init>(CrashReport.java:35), app//net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1034), app//net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175), app//net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3221/0x0000000801364040.run(Unknown Source), java.base@14.0.2/java.lang.Thread.run(Thread.java:832)], RUNNABLE Log4j2-TF-1-AsyncLogger[AsyncContext@5bc2b487]-1: [java.base@14.0.2/java.lang.Throwable.getOurStackTrace(Throwable.java:838), java.base@14.0.2/java.lang.Throwable.getStackTrace(Throwable.java:832), app//org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:138), app//org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:122), app//org.apache.logging.log4j.core.async.RingBufferLogEvent.getThrownProxy(RingBufferLogEvent.java:330), app//org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:61), app//org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38), app//org.apache.logging.log4j.core.layout.PatternLayout$PatternSelectorSerializer.toSerializable(PatternLayout.java:455), app//org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:232), app//org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:217), app//org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:57), app//org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:177), app//org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170), app//org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161), app//org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender.append(RollingRandomAccessFileAppender.java:218), app//org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156), app//org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129), app//org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120), app//org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84), app//org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448), app//org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433), app//org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417), app//org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:79), app//org.apache.logging.log4j.core.async.AsyncLogger.actualAsyncLog(AsyncLogger.java:337), app//org.apache.logging.log4j.core.async.RingBufferLogEvent.execute(RingBufferLogEvent.java:161), app//org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:45), app//org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:29), app//com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168), app//com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630), java.base@14.0.2/java.lang.Thread.run(Thread.java:832)], WAITING Snooper Timer: [java.base@14.0.2/java.lang.Object.wait(Native Method), java.base@14.0.2/java.lang.Object.wait(Object.java:321), java.base@14.0.2/java.util.TimerThread.mainLoop(Timer.java:527), java.base@14.0.2/java.util.TimerThread.run(Timer.java:506)], WAITING Java2D Disposer: [java.base@14.0.2/java.lang.Object.wait(Native Method), java.base@14.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@14.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.desktop@14.0.2/sun.java2d.Disposer.run(Disposer.java:144), java.base@14.0.2/java.lang.Thread.run(Thread.java:832)], TIMED_WAITING Craft Scheduler Thread - 3: [java.base@14.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@14.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@14.0.2/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462), java.base@14.0.2/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361), java.base@14.0.2/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1055), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1116), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630), java.base@14.0.2/java.lang.Thread.run(Thread.java:832)], WAITING Paper Async Chunk Task Thread #2: [java.base@14.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@14.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], WAITING Paper Async Chunk Task Thread #1: [java.base@14.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@14.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], WAITING Worker-Main-2: [java.base@14.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@14.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@14.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:505), java.base@14.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3137), java.base@14.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1614), java.base@14.0.2/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1056), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1116), java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630), java.base@14.0.2/java.lang.Thread.run(Thread.java:832)], WAITING Finalizer: [java.base@14.0.2/java.lang.Object.wait(Native Method), java.base@14.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@14.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.base@14.0.2/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)], TIMED_WAITING Paper Watchdog Thread: [java.base@14.0.2/java.lang.Thread.sleep(Native Method), app//org.spigotmc.WatchdogThread.run(WatchdogThread.java:170)], RUNNABLE Netty Epoll Server IO #0: [app//io.netty.channel.epoll.Native.epollWait(Native Method), app//io.netty.channel.epoll.Native.epollWait(Native.java:148), app//io.netty.channel.epoll.Native.epollWait(Native.java:141), app//io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:290), app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:347), app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989), app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), java.base@14.0.2/java.lang.Thread.run(Thread.java:832)], RUNNABLE DestroyJavaVM: [], RUNNABLE Signal Dispatcher: [],}
   
   Force Loaded Chunks: { world: {}, world_nether: {},}
	Player Count: 0 / 5; []
	Data Packs: vanilla, file/bukkit, file/bonsaipots (incompatible), file/deathcoordinates (incompatible), file/javd (incompatible), file/qi, file/timber, file/better_mob_armor, file/betterstorage (incompatible), file/creeper_dungeon, file/elevator (incompatible), file/gravestones, file/honeypunk_expansion, file/items (incompatible), file/items-plus (incompatible), file/mobcaptains, file/overhauledbats, file/platypack_recipes_advancements, file/pvpplayerheads, file/spegtunerpg, file/stonecraftables, file/vanillaplus (incompatible), file/diamondstonecutter (incompatible), file/furnace_plus (incompatible), file/ggunz, file/goldstonecutter (incompatible), file/ironstonecutter (incompatible), file/mcrgearoverhaul, file/dungeon_now_loading, file/stoo_survival
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)
```

**Comment by NorbiPeti** [comment]
That's an interesting error. I looked at that datapack and I don't think it has any dimensions by itself. The Far End datapack that adds to it also just changes the end dimension. What version of the datapack are you using? Are you sure it's caused by this datapack?

Either way, this crash shouldn't happen, did you use any reload commands? Does the crash only happen with my plugin installed?

**Comment by maicol07** [comment]
@NorbiPeti removing that datapack lets the server start. With that datapack it doesn't work, with or without the CustomDimensions plugin

**Comment by NorbiPeti** [comment]
I managed to reproduce this issue. The version on planetminecraft seems to be for 1.17 snapshots, you need to join their Discord server for 1.16 versions.
